from artiq.experiment import *
import numpy as np
from PyQt5 import QtCore, QtGui, QtWidgets
import os
import sys


class GUITest2(EnvExperiment, object):
    """GUIFinal"""
    def build(self):
        pass
        
    def run(self):
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        self.setupUi(MainWindow) 
        MainWindow.show()
        sys.exit(app.exec_()) 
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(678, 887)
        font = QtGui.QFont()
        font.setFamily("Arial")
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(40, 90, 611, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(310, 275, 41, 561))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 270, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 345, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 405, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 465, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.doubleSpinBox_rabistart = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_rabistart.setGeometry(QtCore.QRect(160, 335, 101, 41))
        self.doubleSpinBox_rabistart.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_rabistart.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_rabistart.setMaximum(999999.99)
        self.doubleSpinBox_rabistart.setObjectName("doubleSpinBox_rabistart")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(280, 345, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.doubleSpinBox_rabiend = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_rabiend.setGeometry(QtCore.QRect(160, 395, 101, 41))
        self.doubleSpinBox_rabiend.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_rabiend.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_rabiend.setMaximum(999999.99)
        self.doubleSpinBox_rabiend.setObjectName("doubleSpinBox_rabiend")
        self.doubleSpinBox_rabistep = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_rabistep.setGeometry(QtCore.QRect(160, 455, 101, 41))
        self.doubleSpinBox_rabistep.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_rabistep.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_rabistep.setMaximum(999999.99)
        self.doubleSpinBox_rabistep.setObjectName("doubleSpinBox_rabistep")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(280, 405, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(280, 465, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(50, 530, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(310, 675, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.spinBox_rabirepeat = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_rabirepeat.setGeometry(QtCore.QRect(160, 530, 71, 31))
        self.spinBox_rabirepeat.setObjectName("spinBox_rabirepeat")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(30, 580, 621, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(360, 345, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(620, 465, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(360, 530, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(360, 405, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(360, 465, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.doubleSpinBox_zeemanstep = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_zeemanstep.setGeometry(QtCore.QRect(500, 455, 101, 41))
        self.doubleSpinBox_zeemanstep.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_zeemanstep.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_zeemanstep.setMaximum(999999.99)
        self.doubleSpinBox_zeemanstep.setObjectName("doubleSpinBox_zeemanstep")
        self.spinBox_zeemanrepeat = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_zeemanrepeat.setGeometry(QtCore.QRect(500, 530, 71, 31))
        self.spinBox_zeemanrepeat.setObjectName("spinBox_zeemanrepeat")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(620, 345, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.doubleSpinBox_zeemanstart = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_zeemanstart.setGeometry(QtCore.QRect(500, 335, 101, 41))
        self.doubleSpinBox_zeemanstart.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_zeemanstart.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_zeemanstart.setMaximum(999999.99)
        self.doubleSpinBox_zeemanstart.setObjectName("doubleSpinBox_zeemanstart")
        self.doubleSpinBox_zeemanend = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_zeemanend.setGeometry(QtCore.QRect(500, 395, 101, 41))
        self.doubleSpinBox_zeemanend.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_zeemanend.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_zeemanend.setMaximum(999999.99)
        self.doubleSpinBox_zeemanend.setObjectName("doubleSpinBox_zeemanend")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(620, 405, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(250, 530, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(590, 530, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(-10, 20, 501, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(360, 270, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(50, 730, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(280, 730, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.spinBox_custreapeat = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_custreapeat.setGeometry(QtCore.QRect(160, 795, 71, 31))
        self.spinBox_custreapeat.setObjectName("spinBox_custreapeat")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(50, 590, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(250, 805, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.doubleSpinBox_custTime = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_custTime.setGeometry(QtCore.QRect(160, 720, 101, 41))
        self.doubleSpinBox_custTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_custTime.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_custTime.setMaximum(999999.99)
        self.doubleSpinBox_custTime.setObjectName("doubleSpinBox_custTime")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(50, 805, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.doubleSpinBox_custF = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_custF.setGeometry(QtCore.QRect(160, 660, 101, 41))
        self.doubleSpinBox_custF.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_custF.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_custF.setMaximum(999999.99)
        self.doubleSpinBox_custF.setObjectName("doubleSpinBox_custF")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(50, 670, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(280, 670, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(40, 260, 611, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.doubleSpinBox_DPL = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_DPL.setGeometry(QtCore.QRect(170, 160, 101, 31))
        self.doubleSpinBox_DPL.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_DPL.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_DPL.setMaximum(999999.99)
        self.doubleSpinBox_DPL.setObjectName("doubleSpinBox_DPL")
        self.doubleSpinBox_PMT = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_PMT.setGeometry(QtCore.QRect(170, 210, 101, 31))
        self.doubleSpinBox_PMT.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_PMT.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_PMT.setMaximum(999999.99)
        self.doubleSpinBox_PMT.setObjectName("doubleSpinBox_PMT")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(50, 210, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.doubleSpinBox_SB = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_SB.setGeometry(QtCore.QRect(500, 160, 101, 31))
        self.doubleSpinBox_SB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_SB.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_SB.setMaximum(999999.99)
        self.doubleSpinBox_SB.setObjectName("doubleSpinBox_SB")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(50, 100, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(290, 160, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(620, 160, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(50, 160, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(350, 160, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.doubleSpinBox_GAP = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_GAP.setGeometry(QtCore.QRect(500, 210, 101, 31))
        self.doubleSpinBox_GAP.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doubleSpinBox_GAP.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_GAP.setMaximum(999999.99)
        self.doubleSpinBox_GAP.setObjectName("doubleSpinBox_GAP")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(350, 210, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(290, 210, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(620, 210, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.radioButton_rabi = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_rabi.setGeometry(QtCore.QRect(370, 670, 115, 19))
        self.radioButton_rabi.setObjectName("radioButton_rabi")
        self.radioButton_zeeman = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_zeeman.setGeometry(QtCore.QRect(370, 710, 115, 19))
        self.radioButton_zeeman.setObjectName("radioButton_zeeman")
        self.radioButton_cust = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_cust.setGeometry(QtCore.QRect(370, 750, 115, 19))
        self.radioButton_cust.setObjectName("radioButton_cust")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(360, 590, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(520, 720, 111, 111))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.radioButton_off = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_off.setGeometry(QtCore.QRect(370, 790, 115, 19))
        self.radioButton_off.setObjectName("radioButton_off")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 678, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        #Renewed by MGQ------------------------------------------------------------------------------------------------------------------------------------------------
        #RABI
        self.doubleSpinBox_rabistart.valueChanged.connect(self.doubleSpinBox_rabistart_ChangeValue)
        self.doubleSpinBox_rabiend.valueChanged.connect(self.doubleSpinBox_rabiend_ChangeValue)
        self.doubleSpinBox_rabistep.valueChanged.connect(self.doubleSpinBox_rabistep_ChangeValue)
        self.spinBox_rabirepeat.valueChanged.connect(self.spinBox_rabirepeat_ChangeValue)
        
        #ZEEMAN
        self.doubleSpinBox_zeemanstart.valueChanged.connect(self.doubleSpinBox_zeemanstart_ChangeValue)
        self.doubleSpinBox_zeemanend.valueChanged.connect(self.doubleSpinBox_zeemanend_ChangeValue)
        self.doubleSpinBox_zeemanstep.valueChanged.connect(self.doubleSpinBox_zeemanstep_ChangeValue)
        self.spinBox_zeemanrepeat.valueChanged.connect(self.spinBox_zeemanrepeat_ChangeValue)
        
        #cust
        self.doubleSpinBox_custF.valueChanged.connect(self.doubleSpinBox_custF_ChangeValue)
        self.doubleSpinBox_custTime.valueChanged.connect(self.doubleSpinBox_custTime_ChangeValue)
        self.spinBox_custreapeat.valueChanged.connect(self.spinBox_custreapeat_ChangeValue)
        
        #DFT
        self.doubleSpinBox_DPL.valueChanged.connect(self.doubleSpinBox_DPL_ChangeValue)
        self.doubleSpinBox_SB.valueChanged.connect(self.doubleSpinBox_SB_ChangeValue)
        self.doubleSpinBox_PMT.valueChanged.connect(self.doubleSpinBox_PMT_ChangeValue)
        self.doubleSpinBox_GAP.valueChanged.connect(self.doubleSpinBox_GAP_ChangeValue)
        
        #Selection
        self.radioButton_rabi.toggled.connect(self.on_radio_button_rabi_toggled)
        self.radioButton_zeeman.toggled.connect(self.on_radio_button_zeeman_toggled)
        self.radioButton_cust.toggled.connect(self.on_radio_button_cust_toggled)
        self.radioButton_off.toggled.connect(self.on_radio_button_off_toggled)
        self.pushButton.clicked.connect(self.Bstart)
        
        #RABI_BOX
    def doubleSpinBox_rabistart_ChangeValue(self):
        self.set_dataset("Run_Uint.Rabi.Start",self.doubleSpinBox_rabistart.value(), broadcast=True)
        self.Rabistart=self.doubleSpinBox_rabistart.value()
        
    def doubleSpinBox_rabiend_ChangeValue(self):
        self.set_dataset("Run_Uint.Rabi.End",self.doubleSpinBox_rabiend.value(), broadcast=True)
        self.Rabiend=self.doubleSpinBox_rabiend.value()
        
    def doubleSpinBox_rabistep_ChangeValue(self):
        self.set_dataset("Run_Uint.Rabi.Step",self.doubleSpinBox_rabistep.value(), broadcast=True)
        self.Rabistep=self.doubleSpinBox_rabistep.value()
        
    def spinBox_rabirepeat_ChangeValue(self):
        self.set_dataset("Run_Uint.Rabi.Repeat",self.spinBox_rabirepeat.value(), broadcast=True)
        self.Rabirepeat=self.spinBox_rabirepeat.value()
        
        #ZEEMAN_BOX
    def doubleSpinBox_zeemanstart_ChangeValue(self):
        self.set_dataset("Run_Uint.Zeeman.Start",self.doubleSpinBox_zeemanstart.value(), broadcast=True)
        self.Zeemanstart=self.doubleSpinBox_zeemanstart.value()
        
    def doubleSpinBox_zeemanend_ChangeValue(self):
        self.set_dataset("Run_Uint.Zeeman.End",self.doubleSpinBox_zeemanend.value(), broadcast=True)
        self.Zeemanend=self.doubleSpinBox_zeemanend.value()
        
    def doubleSpinBox_zeemanstep_ChangeValue(self):
        self.set_dataset("Run_Uint.Zeeman.Step",self.doubleSpinBox_zeemanstep.value(), broadcast=True)
        self.Zeemanstep=self.doubleSpinBox_zeemanstep.value()
        
    def spinBox_zeemanrepeat_ChangeValue(self):
        self.set_dataset("Run_Uint.Zeeman.Repeat",self.spinBox_zeemanrepeat.value(), broadcast=True)
        self.Zeemanrepeat=self.spinBox_zeemanrepeat.value()
        
        #cust_BOX
        
    def doubleSpinBox_custF_ChangeValue(self):
        self.set_dataset("Run_Uint.Customized.Start",self.doubleSpinBox_custF.value(), broadcast=True)
        self.custF=self.doubleSpinBox_custF.value()
        
    def doubleSpinBox_custTime_ChangeValue(self):
        self.set_dataset("Run_Uint.Customized.End",self.doubleSpinBox_custTime.value(), broadcast=True)
        self.custTime=self.doubleSpinBox_custTime.value()
        
    def spinBox_custreapeat_ChangeValue(self):
        self.set_dataset("Run_Uint.Customized.Repeat",self.spinBox_custreapeat.value(), broadcast=True)
        self.custrepeat=self.spinBox_custreapeat.value()

        #DFT_BOX
        
    def doubleSpinBox_DPL_ChangeValue(self):
        self.set_dataset("Run_Uint.Default.DPL",self.doubleSpinBox_DPL.value(), broadcast=True)
        self.DPL=self.doubleSpinBox_DPL.value()
        
    def doubleSpinBox_SB_ChangeValue(self):
        self.set_dataset("Run_Uint.Default.SB",self.doubleSpinBox_SB.value(), broadcast=True)
        self.SB=self.doubleSpinBox_SB.value()
        
    def doubleSpinBox_PMT_ChangeValue(self):
        self.set_dataset("Run_Uint.Default.PMT",self.doubleSpinBox_PMT.value(), broadcast=True)
        self.PMT=self.doubleSpinBox_PMT.value()
        
    def doubleSpinBox_GAP_ChangeValue(self):
        self.set_dataset("Run_Uint.Default.GAP",self.doubleSpinBox_GAP.value(), broadcast=True)
        self.GAP=self.doubleSpinBox_GAP.value()
        
    def on_radio_button_rabi_toggled(self):
        if self.radioButton_rabi.isChecked():
            self.para=1
    def on_radio_button_zeeman_toggled(self):
        if self.radioButton_zeeman.isChecked():
            self.para=2
    def on_radio_button_cust_toggled(self):
        if self.radioButton_cust.isChecked():
            self.para=3
    def on_radio_button_off_toggled(self):
        if self.radioButton_off.isChecked():
            self.para=4
            
    def Bstart(self):
        self.set_dataset("para",self.para, broadcast=True)
        
        
    #END------------------------------------------------------------------------------------------------------------------------------------------------------------------
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; color:#002800;\">Rabi Scan</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Time to Start"))
        self.label_3.setText(_translate("MainWindow", "Time to End"))
        self.label_4.setText(_translate("MainWindow", "Time for Step"))
        self.label_5.setText(_translate("MainWindow", "us"))
        self.label_6.setText(_translate("MainWindow", "us"))
        self.label_7.setText(_translate("MainWindow", "us"))
        self.label_9.setText(_translate("MainWindow", "Repeat"))
        self.label_11.setText(_translate("MainWindow", "Frequency of Start"))
        self.label_12.setText(_translate("MainWindow", "Hz"))
        self.label_13.setText(_translate("MainWindow", "Repeat"))
        self.label_14.setText(_translate("MainWindow", "Frequency of End"))
        self.label_15.setText(_translate("MainWindow", "Frequency for Step"))
        self.label_16.setText(_translate("MainWindow", "Hz"))
        self.label_17.setText(_translate("MainWindow", "Hz"))
        self.label_18.setText(_translate("MainWindow", "次"))
        self.label_19.setText(_translate("MainWindow", "次"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#003500;\">Ion Trap QC Control System </span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; color:#002800;\">Zeeman Scan</span></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "Rabi Time"))
        self.label_23.setText(_translate("MainWindow", "us"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#002800;\">Customized</span></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "次"))
        self.label_29.setText(_translate("MainWindow", "Repeat"))
        self.label_22.setText(_translate("MainWindow", "Frequency "))
        self.label_28.setText(_translate("MainWindow", "Hz"))
        self.label_31.setText(_translate("MainWindow", "Time for PMT "))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#002800;\">Default Setting</span></p></body></html>"))
        self.label_36.setText(_translate("MainWindow", "us"))
        self.label_30.setText(_translate("MainWindow", "us"))
        self.label_37.setText(_translate("MainWindow", "Doppler Cooling"))
        self.label_38.setText(_translate("MainWindow", "Side Band Cooling"))
        self.label_34.setText(_translate("MainWindow", "Gap"))
        self.label_39.setText(_translate("MainWindow", "us"))
        self.label_40.setText(_translate("MainWindow", "us"))
        self.radioButton_rabi.setText(_translate("MainWindow", "Rabi Scan"))
        self.radioButton_zeeman.setText(_translate("MainWindow", "Zeeman Scan"))
        self.radioButton_cust.setText(_translate("MainWindow", "Customized"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#002800;\">Selection</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))
        self.radioButton_off.setText(_translate("MainWindow", "OFF"))
        
        
        
    
