# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\QC\Desktop\GUI\rabi.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!

from artiq.experiment import *
import numpy as np
from PyQt5 import QtCore, QtGui, QtWidgets
import time
import os
import sys

class GUI_Reveal(EnvExperiment,object):
    """GUI Reveal"""
    def build(self):
        self.setattr_device("core")
        self.setattr_device("ttl0")
        self.setattr_device("ttl1")
        self.setattr_device("ttl2")
        self.setattr_device("ttl3")
        self.setattr_device("urukul1_ch0")
        self.setattr_device("ttl4")
        
    def pepare(self):
        pass
    
        
    def run(self):     
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        self.setupUi(MainWindow)    
        MainWindow.show()
        sys.exit(app.exec_())
      
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1759, 834)
        font = QtGui.QFont()
        font.setPointSize(15)
        Form.setFont(font)
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(940, 90, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(950, 40, 130, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(1090, 130, 54, 20))
        self.label_18.setObjectName("label_18")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox.setGeometry(QtCore.QRect(960, 120, 121, 44))
        self.doubleSpinBox.setDecimals(4)
        self.doubleSpinBox.setMaximum(500.0)
        self.doubleSpinBox.setProperty("value", 411.2379)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(960, 180, 121, 44))
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(1090, 190, 54, 20))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(880, 190, 70, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(1180, 40, 130, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalSlider_2 = QtWidgets.QSlider(Form)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(1170, 90, 160, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(1190, 120, 121, 44))
        self.doubleSpinBox_5.setDecimals(4)
        self.doubleSpinBox_5.setMaximum(900.99)
        self.doubleSpinBox_5.setProperty("value", 755.1447)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(1320, 130, 54, 20))
        self.label_22.setObjectName("label_22")
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(1190, 180, 121, 44))
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(1320, 190, 54, 20))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(930, 320, 74, 25))
        self.label_24.setObjectName("label_24")
        self.spinBox_6 = QtWidgets.QSpinBox(Form)
        self.spinBox_6.setGeometry(QtCore.QRect(1020, 310, 121, 44))
        self.spinBox_6.setObjectName("spinBox_6")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(1150, 320, 54, 20))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(1190, 320, 74, 25))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(1410, 320, 54, 20))
        self.label_27.setObjectName("label_27")
        self.spinBox_7 = QtWidgets.QSpinBox(Form)
        self.spinBox_7.setGeometry(QtCore.QRect(1280, 310, 121, 44))
        self.spinBox_7.setObjectName("spinBox_7")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(980, 480, 91, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout.addWidget(self.radioButton_4)
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(0, 470, 491, 371))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(180, 10, 140, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(130, 70, 41, 20))
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setGeometry(QtCore.QRect(190, 60, 101, 44))
        self.spinBox.setMinimum(10)
        self.spinBox.setMaximum(1000)
        self.spinBox.setObjectName("spinBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(0, 150, 80, 20))
        self.label_2.setObjectName("label_2")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_2.setGeometry(QtCore.QRect(100, 140, 101, 44))
        self.spinBox_2.setMinimum(10)
        self.spinBox_2.setMaximum(1000)
        self.spinBox_2.setObjectName("spinBox_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(210, 150, 54, 20))
        self.label_7.setObjectName("label_7")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_3.setGeometry(QtCore.QRect(340, 140, 101, 44))
        self.spinBox_3.setMinimum(1000)
        self.spinBox_3.setMaximum(2000)
        self.spinBox_3.setObjectName("spinBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(240, 150, 80, 20))
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(450, 150, 54, 20))
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(130, 230, 41, 20))
        self.label_5.setObjectName("label_5")
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_4.setGeometry(QtCore.QRect(190, 220, 101, 44))
        self.spinBox_4.setObjectName("spinBox_4")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(300, 230, 54, 20))
        self.label_16.setObjectName("label_16")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(180, 300, 131, 41))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(490, 470, 491, 371))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setGeometry(QtCore.QRect(160, 10, 170, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_2)
        self.label_29.setGeometry(QtCore.QRect(130, 70, 41, 20))
        self.label_29.setObjectName("label_29")
        self.spinBox_9 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_9.setGeometry(QtCore.QRect(190, 60, 101, 44))
        self.spinBox_9.setMinimum(10)
        self.spinBox_9.setMaximum(1000)
        self.spinBox_9.setObjectName("spinBox_9")
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        self.label_30.setGeometry(QtCore.QRect(0, 150, 80, 20))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.groupBox_2)
        self.label_31.setGeometry(QtCore.QRect(210, 150, 54, 20))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        self.label_32.setGeometry(QtCore.QRect(250, 150, 80, 20))
        self.label_32.setObjectName("label_32")
        self.label_34 = QtWidgets.QLabel(self.groupBox_2)
        self.label_34.setGeometry(QtCore.QRect(90, 230, 81, 20))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        self.label_35.setGeometry(QtCore.QRect(300, 230, 54, 20))
        self.label_35.setObjectName("label_35")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(180, 300, 131, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_7.setGeometry(QtCore.QRect(90, 140, 121, 44))
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_8.setGeometry(QtCore.QRect(340, 140, 121, 44))
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_9.setGeometry(QtCore.QRect(190, 220, 101, 44))
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.label_33 = QtWidgets.QLabel(Form)
        self.label_33.setGeometry(QtCore.QRect(950, 620, 54, 20))
        self.label_33.setObjectName("label_33")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(1070, 480, 91, 351))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radioButton_17 = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton_17.setFont(font)
        self.radioButton_17.setObjectName("radioButton_17")
        self.verticalLayout_5.addWidget(self.radioButton_17)
        self.radioButton_18 = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton_18.setFont(font)
        self.radioButton_18.setObjectName("radioButton_18")
        self.verticalLayout_5.addWidget(self.radioButton_18)
        self.radioButton_19 = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton_19.setFont(font)
        self.radioButton_19.setObjectName("radioButton_19")
        self.verticalLayout_5.addWidget(self.radioButton_19)
        self.radioButton_20 = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton_20.setFont(font)
        self.radioButton_20.setObjectName("radioButton_20")
        self.verticalLayout_5.addWidget(self.radioButton_20)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(1160, 480, 91, 351))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.radioButton_21 = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton_21.setFont(font)
        self.radioButton_21.setObjectName("radioButton_21")
        self.verticalLayout_6.addWidget(self.radioButton_21)
        self.radioButton_22 = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton_22.setFont(font)
        self.radioButton_22.setObjectName("radioButton_22")
        self.verticalLayout_6.addWidget(self.radioButton_22)
        self.radioButton_23 = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton_23.setFont(font)
        self.radioButton_23.setObjectName("radioButton_23")
        self.verticalLayout_6.addWidget(self.radioButton_23)
        self.radioButton_24 = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.radioButton_24.setFont(font)
        self.radioButton_24.setObjectName("radioButton_24")
        self.verticalLayout_6.addWidget(self.radioButton_24)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(1250, 480, 91, 351))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_6 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_3.addWidget(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_3.addWidget(self.radioButton_7)
        self.radioButton_11 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_11.setObjectName("radioButton_11")
        self.verticalLayout_3.addWidget(self.radioButton_11)
        self.radioButton_12 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_12.setObjectName("radioButton_12")
        self.verticalLayout_3.addWidget(self.radioButton_12)
        self.radioButton_8 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout_3.addWidget(self.radioButton_8)
        self.radioButton_10 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_10.setObjectName("radioButton_10")
        self.verticalLayout_3.addWidget(self.radioButton_10)
        self.radioButton_9 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_9.setObjectName("radioButton_9")
        self.verticalLayout_3.addWidget(self.radioButton_9)
        self.radioButton_5 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_3.addWidget(self.radioButton_5)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(1340, 480, 101, 351))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButton_15 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_15.setObjectName("radioButton_15")
        self.verticalLayout_4.addWidget(self.radioButton_15)
        self.radioButton_14 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_14.setObjectName("radioButton_14")
        self.verticalLayout_4.addWidget(self.radioButton_14)
        self.radioButton_16 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_16.setObjectName("radioButton_16")
        self.verticalLayout_4.addWidget(self.radioButton_16)
        self.radioButton_27 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_27.setObjectName("radioButton_27")
        self.verticalLayout_4.addWidget(self.radioButton_27)
        self.radioButton_28 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_28.setObjectName("radioButton_28")
        self.verticalLayout_4.addWidget(self.radioButton_28)
        self.radioButton_13 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_13.setObjectName("radioButton_13")
        self.verticalLayout_4.addWidget(self.radioButton_13)
        self.radioButton_26 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_26.setObjectName("radioButton_26")
        self.verticalLayout_4.addWidget(self.radioButton_26)
        self.radioButton_25 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_25.setObjectName("radioButton_25")
        self.verticalLayout_4.addWidget(self.radioButton_25)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(1440, 480, 101, 351))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.radioButton_29 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_29.setObjectName("radioButton_29")
        self.verticalLayout_7.addWidget(self.radioButton_29)
        self.radioButton_30 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_30.setObjectName("radioButton_30")
        self.verticalLayout_7.addWidget(self.radioButton_30)
        self.radioButton_31 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_31.setObjectName("radioButton_31")
        self.verticalLayout_7.addWidget(self.radioButton_31)
        self.radioButton_32 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_32.setObjectName("radioButton_32")
        self.verticalLayout_7.addWidget(self.radioButton_32)
        self.radioButton_33 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_33.setObjectName("radioButton_33")
        self.verticalLayout_7.addWidget(self.radioButton_33)
        self.radioButton_34 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_34.setObjectName("radioButton_34")
        self.verticalLayout_7.addWidget(self.radioButton_34)
        self.radioButton_35 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_35.setObjectName("radioButton_35")
        self.verticalLayout_7.addWidget(self.radioButton_35)
        self.radioButton_36 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_36.setObjectName("radioButton_36")
        self.verticalLayout_7.addWidget(self.radioButton_36)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(1540, 480, 101, 351))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.radioButton_37 = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        self.radioButton_37.setObjectName("radioButton_37")
        self.verticalLayout_8.addWidget(self.radioButton_37)
        self.radioButton_38 = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        self.radioButton_38.setObjectName("radioButton_38")
        self.verticalLayout_8.addWidget(self.radioButton_38)
        self.radioButton_39 = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        self.radioButton_39.setObjectName("radioButton_39")
        self.verticalLayout_8.addWidget(self.radioButton_39)
        self.radioButton_40 = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        self.radioButton_40.setObjectName("radioButton_40")
        self.verticalLayout_8.addWidget(self.radioButton_40)
        self.radioButton_41 = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        self.radioButton_41.setObjectName("radioButton_41")
        self.verticalLayout_8.addWidget(self.radioButton_41)
        self.radioButton_42 = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        self.radioButton_42.setObjectName("radioButton_42")
        self.verticalLayout_8.addWidget(self.radioButton_42)
        self.radioButton_43 = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        self.radioButton_43.setObjectName("radioButton_43")
        self.verticalLayout_8.addWidget(self.radioButton_43)
        self.radioButton_44 = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        self.radioButton_44.setObjectName("radioButton_44")
        self.verticalLayout_8.addWidget(self.radioButton_44)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(1640, 480, 101, 351))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.radioButton_45 = QtWidgets.QRadioButton(self.verticalLayoutWidget_8)
        self.radioButton_45.setObjectName("radioButton_45")
        self.verticalLayout_9.addWidget(self.radioButton_45)
        self.radioButton_46 = QtWidgets.QRadioButton(self.verticalLayoutWidget_8)
        self.radioButton_46.setObjectName("radioButton_46")
        self.verticalLayout_9.addWidget(self.radioButton_46)
        self.radioButton_47 = QtWidgets.QRadioButton(self.verticalLayoutWidget_8)
        self.radioButton_47.setObjectName("radioButton_47")
        self.verticalLayout_9.addWidget(self.radioButton_47)
        self.radioButton_48 = QtWidgets.QRadioButton(self.verticalLayoutWidget_8)
        self.radioButton_48.setObjectName("radioButton_48")
        self.verticalLayout_9.addWidget(self.radioButton_48)
        self.radioButton_49 = QtWidgets.QRadioButton(self.verticalLayoutWidget_8)
        self.radioButton_49.setObjectName("radioButton_49")
        self.verticalLayout_9.addWidget(self.radioButton_49)
        self.radioButton_50 = QtWidgets.QRadioButton(self.verticalLayoutWidget_8)
        self.radioButton_50.setObjectName("radioButton_50")
        self.verticalLayout_9.addWidget(self.radioButton_50)
        self.radioButton_51 = QtWidgets.QRadioButton(self.verticalLayoutWidget_8)
        self.radioButton_51.setObjectName("radioButton_51")
        self.verticalLayout_9.addWidget(self.radioButton_51)
        self.radioButton_52 = QtWidgets.QRadioButton(self.verticalLayoutWidget_8)
        self.radioButton_52.setObjectName("radioButton_52")
        self.verticalLayout_9.addWidget(self.radioButton_52)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(930, 430, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(760, 20, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(1380, 30, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalScrollBar = QtWidgets.QScrollBar(Form)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(470, 160, 160, 16))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(750, 260, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalScrollBar_2 = QtWidgets.QScrollBar(Form)
        self.horizontalScrollBar_2.setGeometry(QtCore.QRect(1470, 100, 160, 16))
        self.horizontalScrollBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_2.setObjectName("horizontalScrollBar_2")
        self.spinBox.setValue(1000)
        self.spinBox.valueChanged.connect(self.changeValue1)
        self.spinBox_2.valueChanged.connect(self.changeValue2)
        self.spinBox_3.valueChanged.connect(self.changeValue3)
        self.spinBox_4.valueChanged.connect(self.changeValue4)
        self.spinBox_9.valueChanged.connect(self.changeValue9)
        self.doubleSpinBox_7.valueChanged.connect(self.ChangeValue7)
        self.doubleSpinBox_8.valueChanged.connect(self.ChangeValue8)
        self.doubleSpinBox_9.valueChanged.connect(self.ChangeValue9)
        self.pushButton.clicked.connect(self.Run_Rabi)
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    
    
    def Run_Rabi(self):
        self.init(blind=False)
        self.Rabi()
    
    
    @kernel
    def init(self, blind=False):
        """Initialize and detect Urukul.

        Resets the DDS I/O interface and verifies correct CPLD gateware
        version.
        Does not pulse the DDS MASTER_RESET as that confuses the AD9910.

        :param blind: Do not attempt to verify presence and compatibility.
        """
        cfg = self.cfg_reg
        # Don't pulse MASTER_RESET (m-labs/artiq#940)
        self.cfg_reg = cfg | (0 << CFG_RST) | (1 << CFG_IO_RST)
        if blind:
            self.cfg_write(self.cfg_reg)
        else:
            proto_rev = urukul_sta_proto_rev(self.sta_read())
            if proto_rev != STA_PROTO_REV_MATCH:
                raise ValueError("Urukul proto_rev mismatch")
        delay(100*us)  # reset, slack
        self.cfg_write(cfg)
        if self.sync_div:
            at_mu(now_mu() & ~0xf)  # align to RTIO/2
            self.set_sync_div(self.sync_div)  # 125 MHz/2 = 1 GHz/16
        delay(1*ms)  # DDS wake up
    
    @kernel
    def Rabi(self):
        self.core.reset()
        delay(10*ms)
        self.urukul1_cpld.init()
        self.urukul1_ch0.init()
        self.urukul1_ch0.sw.on()
        self.urukul1_ch0.set_att(5.0)
        delay(100*ms)
        try:
            self.urukul1_ch0.set(200*MHz)
            delay(30000*ms)
            self.urukul1_ch0.sw.off()
        
        except RTIOUnderflow:
            print("Error for time")
        
    def changeValue1(self):
        self.set_dataset("Run_RABI.Round",self.spinBox.value(), broadcast=True)
        self.Rabi_Round=self.get_dataset("Run_RABI.Round")
        
    def changeValue2(self):
        self.set_dataset("Run_RABI.RABI_TIME_start",self.spinBox_2.value(), broadcast=True)
        self.Rabi_Time_Start=self.get_dataset("Run_RABI.RABI_TIME_start")
        
    def changeValue3(self):
        self.set_dataset("Run_RABI.RABI_TIME_end",self.spinBox_3.value(), broadcast=True)
        self.Rabi_Time_End=self.get_dataset("Run_RABI.RABI_TIME_end")
        
    def changeValue4(self):
        self.set_dataset("Run_RABI.RABI_TIME_step",self.spinBox_4.value(), broadcast=True)
        self.Rabi_Time_Step=self.get_dataset("Run_RABI.RABI_TIME_step")
        
    def changeValue9(self):
        self.set_dataset("Run_ZEEMAN.Round",self.spinBox_9.value(), broadcast=True)
        self.Zeeman_Round=self.get_dataset("Run_ZEEMAN.Round")
        
    def ChangeValue7(self):
        self.set_dataset("Run_ZEEMAN.ZEEMAN_FREQUENCY_start",self.doubleSpinBox_7.value(), broadcast=True)
        self.Zeeman_Frequency_Start=self.get_dataset("Run_ZEEMAN.ZEEMAN_FREQUENCY_start")
        
    def ChangeValue8(self):
        self.set_dataset("Run_ZEEMAN.ZEEMAN_FREQUENCY_end",self.doubleSpinBox_8.value(), broadcast=True)
        self.Zeeman_Frequency_End=self.get_dataset("Run_ZEEMAN.ZEEMAN_FREQUENCY_end")
        
    def ChangeValue9(self):
        self.set_dataset("Run_ZEEMAN.ZEEMAN_FREQUENCY_step",self.doubleSpinBox_9.value(), broadcast=True)
        self.Zeeman_Frequency_Step=self.get_dataset("Run_ZEEMAN.ZEEMAN_FREQUENCY_step")
    
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_17.setText(_translate("Form", "729nm激光频率"))
        self.label_18.setText(_translate("Form", "THz"))
        self.label_19.setText(_translate("Form", "THz"))
        self.label_20.setText(_translate("Form", "失谐量"))
        self.label_21.setText(_translate("Form", "397nm激光频率"))
        self.label_22.setText(_translate("Form", "THz"))
        self.label_23.setText(_translate("Form", "THz"))
        self.label_24.setText(_translate("Form", "DPL时长"))
        self.label_25.setText(_translate("Form", "ms"))
        self.label_26.setText(_translate("Form", "SBL时长"))
        self.label_27.setText(_translate("Form", "ms"))
        self.radioButton_3.setText(_translate("Form", "DDS0"))
        self.radioButton_2.setText(_translate("Form", "DDS1"))
        self.radioButton_4.setText(_translate("Form", "DDS2"))
        self.radioButton.setText(_translate("Form", "DDS3"))
        self.groupBox.setTitle(_translate("Form", "GroupBox"))
        self.label_3.setText(_translate("Form", "Rabi Scan"))
        self.label.setText(_translate("Form", "回合数"))
        self.label_2.setText(_translate("Form", "开始时长"))
        self.label_7.setText(_translate("Form", "ms"))
        self.label_4.setText(_translate("Form", "结束时长"))
        self.label_8.setText(_translate("Form", "ms"))
        self.label_5.setText(_translate("Form", "步长"))
        self.label_16.setText(_translate("Form", "ms"))
        self.pushButton.setText(_translate("Form", "开始"))
        self.groupBox_2.setTitle(_translate("Form", "GroupBox"))
        self.label_28.setText(_translate("Form", "Zeeman Scan"))
        self.label_29.setText(_translate("Form", "回合数"))
        self.label_30.setText(_translate("Form", "开始频率"))
        self.label_31.setText(_translate("Form", "THz"))
        self.label_32.setText(_translate("Form", "终止频率"))
        self.label_34.setText(_translate("Form", "步长频率"))
        self.label_35.setText(_translate("Form", "THz"))
        self.pushButton_4.setText(_translate("Form", "开始"))
        self.label_33.setText(_translate("Form", "THz"))
        self.radioButton_17.setText(_translate("Form", "DDS4"))
        self.radioButton_18.setText(_translate("Form", "DDS5"))
        self.radioButton_19.setText(_translate("Form", "DDS6"))
        self.radioButton_20.setText(_translate("Form", "DDS7"))
        self.radioButton_21.setText(_translate("Form", "DDS8"))
        self.radioButton_22.setText(_translate("Form", "DDS9"))
        self.radioButton_23.setText(_translate("Form", "DDS10"))
        self.radioButton_24.setText(_translate("Form", "DDS11"))
        self.radioButton_6.setText(_translate("Form", "TTL0"))
        self.radioButton_7.setText(_translate("Form", "TTL1"))
        self.radioButton_11.setText(_translate("Form", "TTL2"))
        self.radioButton_12.setText(_translate("Form", "TTL3"))
        self.radioButton_8.setText(_translate("Form", "TTL4"))
        self.radioButton_10.setText(_translate("Form", "TTL5"))
        self.radioButton_9.setText(_translate("Form", "TTL6"))
        self.radioButton_5.setText(_translate("Form", "TTL7"))
        self.radioButton_15.setText(_translate("Form", "TTL8"))
        self.radioButton_14.setText(_translate("Form", "TTL9"))
        self.radioButton_16.setText(_translate("Form", "TTL10"))
        self.radioButton_27.setText(_translate("Form", "TTL11"))
        self.radioButton_28.setText(_translate("Form", "TTL12"))
        self.radioButton_13.setText(_translate("Form", "TTL13"))
        self.radioButton_26.setText(_translate("Form", "TTL14"))
        self.radioButton_25.setText(_translate("Form", "TTL15"))
        self.radioButton_29.setText(_translate("Form", "TTL16"))
        self.radioButton_30.setText(_translate("Form", "TTL17"))
        self.radioButton_31.setText(_translate("Form", "TTL18"))
        self.radioButton_32.setText(_translate("Form", "TTL19"))
        self.radioButton_33.setText(_translate("Form", "TTL20"))
        self.radioButton_34.setText(_translate("Form", "TTL21"))
        self.radioButton_35.setText(_translate("Form", "TTL22"))
        self.radioButton_36.setText(_translate("Form", "TTL23"))
        self.radioButton_37.setText(_translate("Form", "TTL24"))
        self.radioButton_38.setText(_translate("Form", "TTL25"))
        self.radioButton_39.setText(_translate("Form", "TTL26"))
        self.radioButton_40.setText(_translate("Form", "TTL27"))
        self.radioButton_41.setText(_translate("Form", "TTL28"))
        self.radioButton_42.setText(_translate("Form", "TTL29"))
        self.radioButton_43.setText(_translate("Form", "TTL30"))
        self.radioButton_44.setText(_translate("Form", "TTL31"))
        self.radioButton_45.setText(_translate("Form", "TTL32"))
        self.radioButton_46.setText(_translate("Form", "TTL33"))
        self.radioButton_47.setText(_translate("Form", "TTL34"))
        self.radioButton_48.setText(_translate("Form", "TTL35"))
        self.radioButton_49.setText(_translate("Form", "TTL36"))
        self.radioButton_50.setText(_translate("Form", "TTL37"))
        self.radioButton_51.setText(_translate("Form", "TTL38"))
        self.radioButton_52.setText(_translate("Form", "TTL39"))
        self.label_6.setText(_translate("Form", "DDS与TTL监控"))
        self.label_10.setText(_translate("Form", "激光频率手动设置"))
        self.label_9.setText(_translate("Form", "激光开关手动设置"))
        self.label_11.setText(_translate("Form", "冷却时长及其他参数设置"))
     


        

        



